export default {
  new_invoice: 'New Invoice',
  shop_username: 'Shop Username',
  my_awesome_shop_placeholder: 'myawesomeshop',
  amount: 'Amount',
  amount_placeholder: 'ex. 1.000',
  memo: 'Memo',
  submit: 'Submit',
  toast_confirmed_invoice: 'Invoice confirmed. Received',
  generating: 'Generating...',
  scan_qr_code: 'Scan this QR Code',
  to: 'To',
  checking_confirmation: 'Checking for confirmation in {{countDown}} seconds',
  cancel_invoice: 'Cancel Invoice',
  alert_cancel_title: 'Do you want to cancel it?',
  alert_cancel_body:
    'The invoice will still be visible in the History screen as not confirmed. You can restore it later on if you want.',
  proceed: 'Proceed',
  cancel: 'Cancel',
  payment_success: 'Payment successful!',
  confirmed: 'Confirmed',
  from: 'From',
  created: 'Created',
  no_records_found: 'No records where found.',
  search_box_placeholder: 'Search box',
  unconfirmed: 'Unconfirmed',
  store: 'Store',
  try_again: 'Try again',
  delete: 'Delete',
  danger_zone: 'Danger Zone',
  delete_all_data: 'Delete All Data',
  alert_box_header_caution: 'Proceed with caution',
  alert_box_body_deletion:
    'Do you want to wipe all data from the app? This will erase all data definetely.',
  confirm_delete: 'Yes, Delete',
  data_deleted: 'All Data deleted from phone.',
  language_settings: 'Language Settings',
};
