export default {
  new_invoice: 'Nueva Factura',
  shop_username: 'Tienda',
  my_awesome_shop_placeholder: 'miasombrosatienda',
  amount: 'Monto',
  amount_placeholder: 'ej. 1.000',
  memo: 'Memo',
  submit: 'Enviar',
  toast_confirmed_invoice: 'Factura confirmada. Recibida',
  generating: 'Generando...',
  scan_qr_code: 'Escanee este código QR',
  to: 'Destinatario',
  checking_confirmation: 'Verificando confirmación en {{countDown}} segundos',
  cancel_invoice: 'Cancelar factura',
  alert_cancel_title: 'Desea usted cancelarlo?',
  alert_cancel_body:
    'La factura seguirá visible en la pantalla Historial como no confirmada. Si lo desea, puede restablecerla más adelante.',
  proceed: 'Proceder',
  cancel: 'Cancelar',
  payment_success: 'Pago exitoso!',
  confirmed: 'Confirmado',
  from: 'Envía',
  created: 'Creado',
  no_records_found: 'No se encontraron registros.',
  search_box_placeholder: 'Caja de búsqueda',
  unconfirmed: 'No confirmado',
  store: 'Tienda',
  try_again: 'Reintentar',
  delete: 'Borrar',
  danger_zone: 'Zona Peligrosa',
  delete_all_data: 'Borrar toda la data',
  alert_box_header_caution: 'Continúe con precaución',
  alert_box_body_deletion:
    '¿Quieres borrar todos los datos de la aplicación? Esto borrará todos los datos definitivamente.',
  confirm_delete: 'Si, Borrar',
  data_deleted: 'Todos los datos borrados del teléfono.',
  language_settings: 'Ajustes de idioma',
};
