export default {
  new_invoice: 'Nueva Factura',
  shop_username: 'Tienda',
  my_awesome_shop_placeholder: 'Descripción',
  amount: 'Monto',
  amount_placeholder: '1.000',
  memo: 'Memo',
  submit: 'Enviar',
  generating: 'Generando...',
  scan_qr_code: 'Escanee este código QR',
  to: 'Destinatario',
  checking_confirmation: 'Verificando confirmación en {{countDown}} segundos',
  cancel_invoice: 'Cancelar factura',
  alert_cancel_title: 'Desea usted cancelarlo?',
  alert_cancel_body:
    'La factura seguirá visible en la pantalla Historial como no confirmada. Si lo desea, puede restablecerla más adelante.',
  proceed: 'Proceder',
  cancel: 'Cancelar',
  payment_success: 'Pago exitoso!',
  confirmed: 'Confirmado',
  from: 'Envía',
  created: 'Creado',
  no_records_found: 'No se encontraron registros.',
  search_box_placeholder: 'Ingrese filtros',
  unconfirmed: 'No confirmado',
  store: 'Tienda',
  try_again: 'Reintentar',
  delete: 'Borrar',
  filter: 'Filtro',
};
